sudo: false
language: php
php:
- 5.6
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bin/travis_github_authenticate.sh
- cp app/config/parameters.yml.dist app/config/parameters.yml
- sed -i 's/%database_name%/%database_name%_test/' app/config/base_config.yml
- mysql -e 'create database overwatch_test;'
- composer install --prefer-dist
- wget -P bin/ http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar
- php app/console doctrine:schema:create --env=test
- java -jar bin/selenium-server-standalone-2.47.0.jar > /dev/null 2>&1 &
- php app/console server:start
script:
- phpunit -c app/
- php vendor/scrutinizer/ocular/bin/ocular code-coverage:upload --format=php-clover /tmp/coverage.clover
before_deploy:
- git reset --hard HEAD && git clean -xdfe app/config/parameters.yml app/ bin/
- composer install --no-dev --prefer-dist
- rm -rf app/cache/* app/logs/* app/config/parameters.yml.dist
- tar -chzf overwatch-$TRAVIS_TAG.tar.gz app/ composer* *.md LICENSE src/ vendor/ web/
deploy:
  provider: releases
  api_key:
    secure: E8e5xwnkbMruKeWFH4t2enUxsAkulSP+KhTrWxpYBe9uU7oG6i9/pQOWIf5XZYFMjtALSNpaIBwJ9mibD5ZatZA5oelFkS0upes4P8NmCohjemdWm9QcH5vcweGzAeNLFFIz9wcuWpiiu+RB137RddTVTkWCFolzucSSu66pvfE=
  file: overwatch-$TRAVIS_TAG.tar.gz
  on:
    tags: true
  skip_cleanup: true
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+/
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
env:
  global:
    secure: OoMBMuFgb3Ha+olcK1AeH+tTlCh/jDS5cDBFAs5Zp8CCqE7pjt1PxqY5DjuUweRDiIwCouoSRJLcr1Trw2/DMW9pTkZv2PdFWgvdlQInddQPVWNAg0C7PHp9EmFdXp8CeuqraqxDx3QrB9ZcPVv+F5Y2eJNQMO8r7OUY71nLZC4=
